import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {GeoJSON,MapContainer,Marker,Popup,TileLayer,useMap,useMapEvents} from 'react-leaflet';
import L from 'leaflet';
import type {Feature,FeatureCollection,Point} from 'geojson';
import 'leaflet/dist/leaflet.css';
import './style.css';
import './options.css';

type Result={name:string;profile:string;warning:string;source_status:string;statistics:{distance_m:number;ascent_m:number;uncertain_percent:number;coverage_percent:number;by_class_m:Record<string,number>};geojson:FeatureCollection};
type BaseMap='standard'|'topo'|'humanitarian'|'satellite';
type PointKind='access'|'start'|'aid'|'vehicle'|'danger'|'other';
type Tool={mode:'none'}|{mode:'add';kind:PointKind}|{mode:'streetview'};
type OperationalPoint={id:string;kind:PointKind;lat:number;lon:number};

const colors:Record<string,string>={green:'#1f9d55',orange:'#e79024',red:'#d64242',gray:'#7a8491'};
const pointTypes:Record<PointKind,{icon:string;label:string;color:string}>={
  access:{icon:'🚑',label:'Accès secours',color:'#087f5b'},start:{icon:'🏁',label:'Départ',color:'#2267a8'},
  aid:{icon:'✚',label:'Poste de secours',color:'#d93434'},vehicle:{icon:'🚒',label:'Véhicule',color:'#e36b18'},
  danger:{icon:'⚠',label:'Danger / obstacle',color:'#b42318'},other:{icon:'●',label:'Autre repère',color:'#5e4aa8'}
};
const maps:Record<BaseMap,{url:string;attribution:string;maxZoom?:number}>={
  standard:{url:'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',attribution:'© OpenStreetMap contributors'},
  topo:{url:'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',attribution:'© OpenStreetMap · SRTM | OpenTopoMap',maxZoom:17},
  humanitarian:{url:'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',attribution:'© OpenStreetMap contributors · HOT'},
  satellite:{url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',attribution:'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics et partenaires',maxZoom:19}
};

function parsePreview(file:File):Promise<FeatureCollection>{return file.text().then(text=>{const xml=new DOMParser().parseFromString(text,'application/xml');if(xml.querySelector('parsererror'))throw Error('Fichier GPX invalide');const lines=[...xml.querySelectorAll('trkseg')].map(seg=>[...seg.querySelectorAll('trkpt')].map(p=>[Number(p.getAttribute('lon')),Number(p.getAttribute('lat'))])).filter(x=>x.length>1);if(!lines.length){const route=[...xml.querySelectorAll('rtept')].map(p=>[Number(p.getAttribute('lon')),Number(p.getAttribute('lat'))]);if(route.length>1)lines.push(route)}if(!lines.length||lines.some(line=>line.some(([lon,lat])=>!Number.isFinite(lon)||!Number.isFinite(lat))))throw Error('Aucune trace exploitable dans ce GPX');return {type:'FeatureCollection',features:[{type:'Feature',properties:{preview:true},geometry:{type:lines.length===1?'LineString':'MultiLineString',coordinates:lines.length===1?lines[0]:lines}}]} as FeatureCollection})}
function FitTrace({data}:{data?:FeatureCollection}){const map=useMap();useEffect(()=>{if(!data?.features.length)return;const bounds=L.geoJSON(data).getBounds();if(bounds.isValid())map.fitBounds(bounds,{padding:[28,28]})},[data,map]);return null}
function MapActions({tool,onAdd,onCoordinate}:{tool:Tool;onAdd:(lat:number,lon:number,kind:PointKind)=>void;onCoordinate:(lat:number,lon:number)=>void}){useMapEvents({click(e){onCoordinate(e.latlng.lat,e.latlng.lng);if(tool.mode==='add')onAdd(e.latlng.lat,e.latlng.lng,tool.kind);if(tool.mode==='streetview'){const point=`${e.latlng.lat},${e.latlng.lng}`;window.open(`https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${encodeURIComponent(point)}`,'_blank','noopener,noreferrer')}}});return null}
function Locate({request,onFound}:{request:number;onFound:(lat:number,lon:number)=>void}){const map=useMap();useEffect(()=>{if(!request)return;map.locate({setView:true,maxZoom:17,enableHighAccuracy:true});const found=(e:L.LocationEvent)=>onFound(e.latlng.lat,e.latlng.lng);map.once('locationfound',found);return()=>{map.off('locationfound',found)}},[request,map,onFound]);return null}
function markerIcon(kind:PointKind){const type=pointTypes[kind];return L.divIcon({className:'op-marker-wrap',html:`<span class="op-marker" style="--marker:${type.color}">${type.icon}</span>`,iconSize:[36,42],iconAnchor:[18,38],popupAnchor:[0,-38]})}

function App(){
  const [file,setFile]=useState<File>();const [preview,setPreview]=useState<FeatureCollection>();const [result,setResult]=useState<Result>();const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [profile,setProfile]=useState('standard');const [baseMap,setBaseMap]=useState<BaseMap>('standard');const [tool,setTool]=useState<Tool>({mode:'none'});const [coordinate,setCoordinate]=useState<[number,number]>();const [locateRequest,setLocateRequest]=useState(0);
  const [points,setPoints]=useState<OperationalPoint[]>(()=>{try{return JSON.parse(localStorage.getItem('gpx-operational-points')||'[]')}catch{return[]}});
  const displayed=useMemo(()=>result?.geojson||preview,[result,preview]);
  useEffect(()=>localStorage.setItem('gpx-operational-points',JSON.stringify(points)),[points]);
  async function selectFile(next?:File){setFile(next);setResult(undefined);setPreview(undefined);setError('');if(!next)return;try{setPreview(await parsePreview(next))}catch(e){setError(e instanceof Error?e.message:'Aperçu impossible')}}
  async function run(){if(!file)return;setLoading(true);setError('');const body=new FormData();body.append('file',file);try{const query=new URLSearchParams({profile});const r=await fetch(`/api/v1/analyze?${query}`,{method:'POST',body});const j=await r.json();if(!r.ok)throw Error(j.detail||'Analyse impossible');setResult(j)}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setLoading(false)}}
  function addPoint(lat:number,lon:number,kind:PointKind){setPoints(old=>[...old,{id:crypto.randomUUID(),kind,lat,lon}])}
  function download(){const markerFeatures:Feature<Point>[] = points.map(p=>({type:'Feature',geometry:{type:'Point',coordinates:[p.lon,p.lat]},properties:{type:p.kind,label:pointTypes[p.kind].label}}));const geojson:FeatureCollection={type:'FeatureCollection',features:[...(result?.geojson.features||preview?.features||[]),...markerFeatures]};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(geojson,null,2)],{type:'application/geo+json'}));a.download=`${result?.name||'carte-operationnelle'}.geojson`;a.click();URL.revokeObjectURL(a.href)}
  function copyCoordinate(){if(coordinate)navigator.clipboard.writeText(`${coordinate[0].toFixed(6)}, ${coordinate[1].toFixed(6)}`)}
  return <main><header><div><span className="mark">✚</span><b>GPX Accès</b><small>Préparation opérationnelle</small></div><span className="badge">Profil · {profile==='standard'?'VL standard':profile==='suv'?'4×4 / SUV':'Secours'}</span></header><section className="layout"><aside><h1>Analyser un parcours</h1><p className="muted">Importez une trace GPX : elle apparaît immédiatement sur la carte.</p><label className="drop"><strong>Déposer un fichier GPX</strong><span>{file?.name||'ou cliquer pour parcourir'}</span><input type="file" accept=".gpx,application/gpx+xml" onChange={e=>selectFile(e.target.files?.[0])}/></label>
  <div className="options"><label>Profil véhicule<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="standard">VL standard</option><option value="suv">4×4 / SUV</option><option value="emergency">Véhicule de secours</option></select></label><label>Fond de carte<select value={baseMap} onChange={e=>setBaseMap(e.target.value as BaseMap)}><option value="standard">Plan OSM</option><option value="satellite">Satellite</option><option value="topo">Topographique</option><option value="humanitarian">Humanitaire détaillé</option></select></label></div><button disabled={!file||loading||!preview} onClick={run}>{loading?'Analyse cartographique en cours…':'Lancer l’analyse'}</button>{error&&<p className="error">{error}</p>}{result?.source_status==='degraded'&&<p className="error">Les services cartographiques sont momentanément indisponibles : le tracé reste visible, mais l’analyse est incomplète.</p>}
  <hr/><h2>Outils opérationnels</h2><p className="hint">Choisissez un repère puis cliquez sur la carte.</p><div className="point-tools">{(Object.keys(pointTypes) as PointKind[]).map(kind=><button key={kind} className={tool.mode==='add'&&tool.kind===kind?'active':''} onClick={()=>setTool({mode:'add',kind})}><span>{pointTypes[kind].icon}</span>{pointTypes[kind].label}</button>)}</div><div className="map-tools"><button className={tool.mode==='streetview'?'active':''} onClick={()=>setTool({mode:'streetview'})}>◉ Street View</button><button onClick={()=>setLocateRequest(x=>x+1)}>⌖ Ma position</button><button onClick={()=>setTool({mode:'none'})}>↖ Navigation</button></div>{coordinate&&<button className="coordinate" onClick={copyCoordinate}>📋 {coordinate[0].toFixed(5)}, {coordinate[1].toFixed(5)}</button>}<div className="tool-footer"><button disabled={!points.length} onClick={()=>setPoints([])}>Effacer les repères</button><button disabled={!displayed&&!points.length} onClick={download}>Exporter la carte</button></div>
  <hr/><h2>Légende de l’analyse</h2>{[['green','Accessible en VL'],['orange','Probablement accessible'],['red','Non accessible'],['gray','Données insuffisantes']].map(([c,t])=><p className="legend" key={c}><i style={{background:colors[c]}}/> {t}</p>)}<div className="warning">⚠ Résultat indicatif. Vérifiez barrières, restrictions, largeur et état du terrain.</div></aside>
  <article className={`tool-${tool.mode}`}><MapContainer center={[45.18,5.72]} zoom={11}><TileLayer key={baseMap} attribution={maps[baseMap].attribution} url={maps[baseMap].url} maxZoom={maps[baseMap].maxZoom}/><FitTrace data={displayed}/><MapActions tool={tool} onAdd={addPoint} onCoordinate={(lat,lon)=>setCoordinate([lat,lon])}/><Locate request={locateRequest} onFound={(lat,lon)=>setCoordinate([lat,lon])}/>{displayed&&<GeoJSON key={`${file?.name}-${result?'result':'preview'}`} data={displayed} style={f=>({color:f?.properties?.preview?'#2878b8':colors[String(f?.properties?.classification)]||colors.gray,weight:result?6:5,dashArray:result?undefined:'8 7'})} onEachFeature={(f,l)=>{if(f.properties&&!f.properties.preview)l.bindPopup(`<b>Score ${f.properties.score}/100</b><br>${(f.properties.reasons||[]).join('<br>')}`)}}/>}{points.map(p=><Marker key={p.id} position={[p.lat,p.lon]} icon={markerIcon(p.kind)} draggable eventHandlers={{dragend:e=>{const ll=e.target.getLatLng();setPoints(old=>old.map(x=>x.id===p.id?{...x,lat:ll.lat,lon:ll.lng}:x))}}}><Popup><b>{pointTypes[p.kind].icon} {pointTypes[p.kind].label}</b><br/>{p.lat.toFixed(6)}, {p.lon.toFixed(6)}<br/><button className="popup-delete" onClick={()=>setPoints(old=>old.filter(x=>x.id!==p.id))}>Supprimer</button></Popup></Marker>)}</MapContainer>{result&&<section className="stats"><div><small>PARCOURS</small><b>{result.name}</b></div><div><small>DISTANCE</small><b>{(result.statistics.distance_m/1000).toFixed(1)} km</b></div><div><small>DÉNIVELÉ +</small><b>{result.statistics.ascent_m.toFixed(0)} m</b></div><div><small>COUVERTURE CARTO</small><b>{result.statistics.coverage_percent}%</b></div><div><small>INCERTAIN</small><b>{result.statistics.uncertain_percent}%</b></div></section>}</article></section></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
